const data = [
    {
        title:"Herman Coat",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    },
    {
        title:"Herman T-shirt",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://i.pinimg.com/originals/2d/af/f8/2daff8e0823e51dd752704a47d5b795c.png",
        categories:["coat"],
        size:["S","M","L"],
        color:["red"],
        price:90,
    },
    {
        title:"Herman Sweater",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow","black"],
        price:87,
    },
    {
        title:"Herman jacket",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    },
    {
        title:"Herman jeans",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    },
    {
        title:"Herman socks",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1614188818-TD1MTHU_SHOE_ANGLE_GLOBAL_MENS_TREE_DASHERS_THUNDER_b01b1013-cd8d-48e7-bed9-52db26515dc4.png?crop=1xw:1.00xh;center,top&resize=480%3A%2A",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    },
    {
        title:"Herman shorts",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    },
    {
        title:"Herman tracksuit",
        desc:"Lorem Ipsum is simply dummy text of the printing...",
        img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
        categories:["women"],
        size:["S","M","L"],
        color:["yellow"],
        price:89,
    }
]

module.exports = data